### ISSUE TITLE
cannot resolve com.adobe.cq.export.json dependency in sample-we-retail-spa-content project

### ISSUE THREAD

**Issue by krchmll** [Adobe-Marketing-Cloud/aem-guides#17]
Running maven install on SRC-sample-we-retail-spa-content throws a unresolved dependency error in **core** module.

[ERROR] Failed to execute goal on project we-retail-journal-core: Could not resolve dependencies for project com.adobe.cq.sample.spa:we-retail-journal-core:bundle:0.2.5-SNAPSHOT: Could not find artifact com.adobe.cq:com.adobe.cq.export.json:jar:0.1.6 in adobe (https://repo.adobe.com/nexus/content/groups/public/)

<dependency>
       <groupId>com.adobe.cq</groupId>
       <artifactId>com.adobe.cq.export.json</artifactId>
       <version>0.1.6</version>
 </dependency>
I have tried with 6.3.2, 6.4.1 aem uber jars but that didn't help (missing hierarchy package).
Can you please let me know where i can get the latest version (0.1.6) of com.adobe.cq.export.json?

**Comment by davidjgonzalez** [comment]
Thanks for the note @krchmll  - ive updated the SRC zip [1], so that the core/pom.xml to depends on the publicly published [2] com.adobe.cq.export.json/0.1.7-CQ-4226752-B006 dependency.

If the problem persists, please re-open the issue and let us know!

[1] https://github.com/Adobe-Marketing-Cloud/aem-guides/blob/master/spa-helloworld-guide/packages/SRC-sample-we-retail-spa-content.zip
[2] https://repo.adobe.com/nexus/content/groups/public/com/adobe/cq/com.adobe.cq.export.json/0.1.7-CQ-4226752-B006/
