### ISSUE TITLE
Getting Started with the AEM SPA Editor - Hello World Tutorial - Package Dependencies

### ISSUE THREAD

**Issue by rnyshadh** [Adobe-Marketing-Cloud/aem-guides#18]
Hi,

I was following Getting Started with the AEM SPA Editor - Hello World Tutorial @Getting Started with the AEM SPA Editor - Hello World Tutorial

1. I did not follow this tutorial step by step, but tried to install the Finished Package END-we-retail-journal-all-0.2.5-SNAPSHOT.zip on my plain AEM 6.4, but got the following error:

"Could not Install Package. Refusing to install package adobe/aem640/sample:we-retail-journal-all:0.2.5-SNAPSHOT. required dependencies missing: [day/cq60/product:cq-ui-wcm-editor-content:(1.0.138,)]".

Kindly suggest.

2. Does this Finished Package also need the SPA Editor Feature Pack, that is currently available through the SPA Editor Beta Program?
I see that the tutorial does.

Appreciate your support.

Thanks,
Rama.

**Comment by davidjgonzalez** [comment]
Correct  - the end result of the tutorial needs the feature pack (else how would it work?)

**Comment by rnyshadh** [comment]
Hi David,

Thanks for responding so fast.

1. So, please confirm that I should install SPA feature Pack on AEM before installing the Finished Package.

2. If I want to take the route of following step by step instructions, where should the SPA feature Pack be used?
This was not described in the tutorial.
I am hearing that step by step instructions are failing at the build level.

Appreciate your support.

Thanks,
Rama.

**Comment by davidjgonzalez** [comment]
Hi 

1. Please install the SPA Editor Feature Pack (available on the SPA Editor Beta Prerelease site) on your AEM instance before deploying the tutorial's code to AEM. (The easy solution is to install it as Step 0 of the tutorial).

2. The SPA Editor Feature Pack installed the SPA Editor framework (including supporting OSGi bundles) to AEM.  The deployment of thee SPA Editor Feature Pack to AEM will not impact your ability to locally build the tutorial project since the maven build depends on the dependencies from the repo.adobe.com maven repository.

If you are failing at the build level, please add the Errors to the GH issue which should help narrow down the problem.
