### ISSUE TITLE
Does this project only work with 6.3?

### ISSUE THREAD

**Issue by shamrox** [Adobe-Marketing-Cloud/aem-guides#2]
I tried many times to put this project in 6.2 but I am getting an issue with:

org.apache.sling.scripting.sightly.SightlyException: Identifier com.adobe.aem.sample.simple.search.SearchResults cannot be correctly instantiated by the Use API

**Comment by godanny86** [comment]
Yes it was developed to be used with 6.3. I think the issue preventing it from working with 6.2 would be the use of [Sling Model Exporter](https://sling.apache.org/documentation/bundles/models.html#exporter-framework-since-130). Not sure if its possible to update the sling model bundle in 6.2 so it supports the jackson exporter...

**Comment by shamrox** [comment]
Hey Danny....you wouldn't happen to have the content you used in the summit? I know it is large but I would love to test and play with that data @godanny86

**Comment by godanny86** [comment]
Hi @shamrox sorry unfortunately we are not able to provide the content that we search upon during summit. However you should be able to search against your own content with only a couple of updates:

1. Update any path restrictions to match /content/<your-content>
2. If you want the filtering/facets to work tag your content using the tags found here [Tags package](https://helpx.adobe.com/content/dam/help/en/adobe-experience-manager/kt/6-3/platform/simple-search-implementation/summit-tags.zip)
